/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  DocSaabLoginAPI,
  docSaabLoginAPISchema,
} from '../models/docSaabLoginAPI';
import {
  DocSaabLoginAPIRequest,
  docSaabLoginAPIRequestSchema,
} from '../models/docSaabLoginAPIRequest';
import { BaseController } from './baseController';

export class MiscController extends BaseController {
  /**
   * localhost:8080/v1/login
   *
   * @param body
   * @return Response from the API call
   */
  async docSaabLoginAPI(
    body: DocSaabLoginAPIRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DocSaabLoginAPI>> {
    const req = this.createRequest('POST', '/auth/login');
    const mapped = req.prepareArgs({
      body: [body, docSaabLoginAPIRequestSchema],
    });
    req.json(mapped.body);
    return req.callAsJson(docSaabLoginAPISchema, requestOptions);
  }
}
