/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

export interface DocSaabDeleteNoteForUserWithNoteId {
  success: boolean;
}

export const docSaabDeleteNoteForUserWithNoteIdSchema: Schema<DocSaabDeleteNoteForUserWithNoteId> = object(
  { success: ['success', boolean()] }
);
