/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, Schema } from '../schema';
import { NoteResponse, noteResponseSchema } from './noteResponse';

export interface DocSaabGetListOfUserNotes {
  success: boolean;
  noteResponse: NoteResponse;
}

export const docSaabGetListOfUserNotesSchema: Schema<DocSaabGetListOfUserNotes> = object(
  {
    success: ['success', boolean()],
    noteResponse: ['noteResponse', lazy(() => noteResponseSchema)],
  }
);
