/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, Schema } from '../schema';
import { NoteResponse1, noteResponse1Schema } from './noteResponse1';

export interface DocSaabCreateUserNote {
  success: boolean;
  noteResponse: NoteResponse1;
}

export const docSaabCreateUserNoteSchema: Schema<DocSaabCreateUserNote> = object(
  {
    success: ['success', boolean()],
    noteResponse: ['noteResponse', lazy(() => noteResponse1Schema)],
  }
);
