/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DocSaabCreateDoctorNoteRequest {
  sessionId: string;
  userId: string;
  doctorId: string;
  noteJson: string;
}

export const docSaabCreateDoctorNoteRequestSchema: Schema<DocSaabCreateDoctorNoteRequest> = object(
  {
    sessionId: ['sessionId', string()],
    userId: ['userId', string()],
    doctorId: ['doctorId', string()],
    noteJson: ['noteJson', string()],
  }
);
