/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface DocSaabLoginAPIRequest {
  email: string;
  password: string;
  roles: string[];
}

export const docSaabLoginAPIRequestSchema: Schema<DocSaabLoginAPIRequest> = object(
  {
    email: ['email', string()],
    password: ['password', string()],
    roles: ['roles', array(string())],
  }
);
