/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, Schema } from '../schema';
import { LoginResponse, loginResponseSchema } from './loginResponse';

export interface DocSaabLoginAPI {
  success: boolean;
  loginResponse: LoginResponse;
}

export const docSaabLoginAPISchema: Schema<DocSaabLoginAPI> = object({
  success: ['success', boolean()],
  loginResponse: ['loginResponse', lazy(() => loginResponseSchema)],
});
