/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, Schema } from '../schema';
import { NoteResponse2, noteResponse2Schema } from './noteResponse2';

export interface DocSaabGetDetailOfUserNotes {
  success: boolean;
  noteResponse: NoteResponse2;
}

export const docSaabGetDetailOfUserNotesSchema: Schema<DocSaabGetDetailOfUserNotes> = object(
  {
    success: ['success', boolean()],
    noteResponse: ['noteResponse', lazy(() => noteResponse2Schema)],
  }
);
