/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DocSaabCreateUserNoteRequest {
  oxygenReading: string;
  feverReading: string;
  bloodPressure: string;
  pulseReading: string;
  comments: string;
  recordedDate: string;
}

export const docSaabCreateUserNoteRequestSchema: Schema<DocSaabCreateUserNoteRequest> = object(
  {
    oxygenReading: ['oxygenReading', string()],
    feverReading: ['feverReading', string()],
    bloodPressure: ['bloodPressure', string()],
    pulseReading: ['pulseReading', string()],
    comments: ['comments', string()],
    recordedDate: ['recordedDate', string()],
  }
);
