/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Token, tokenSchema } from './token';
import { User, userSchema } from './user';

export interface LoginResponse {
  token: Token;
  roles: string[];
  user: User;
}

export const loginResponseSchema: Schema<LoginResponse> = object({
  token: ['token', lazy(() => tokenSchema)],
  roles: ['roles', array(string())],
  user: ['user', lazy(() => userSchema)],
});
