/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Note, noteSchema } from './note';

export interface NoteResponse1 {
  note: Note;
}

export const noteResponse1Schema: Schema<NoteResponse1> = object({
  note: ['note', lazy(() => noteSchema)],
});
