/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Note, noteSchema } from './note';

export interface NoteResponse {
  notes: Note[];
}

export const noteResponseSchema: Schema<NoteResponse> = object({
  notes: ['notes', array(lazy(() => noteSchema))],
});
