/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Notes, notesSchema } from './notes';

export interface NoteResponse2 {
  notes: Notes;
}

export const noteResponse2Schema: Schema<NoteResponse2> = object({
  notes: ['notes', lazy(() => notesSchema)],
});
