/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface Notes {
  id: string;
  userId: string;
  oxygenReading: string;
  feverReading: string;
  bloodPressure: string;
  pulseReading: string;
  comments: string;
  recordedDate: string;
  deleted: boolean;
  flagged: boolean;
  createdAt: string;
  updatedAt: string;
}

export const notesSchema: Schema<Notes> = object({
  id: ['id', string()],
  userId: ['userId', string()],
  oxygenReading: ['oxygenReading', string()],
  feverReading: ['feverReading', string()],
  bloodPressure: ['bloodPressure', string()],
  pulseReading: ['pulseReading', string()],
  comments: ['comments', string()],
  recordedDate: ['recordedDate', string()],
  deleted: ['deleted', boolean()],
  flagged: ['flagged', boolean()],
  createdAt: ['createdAt', string()],
  updatedAt: ['updatedAt', string()],
});
