/**
 * DoctorSabLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Token {
  token: string;
  expires: number;
}

export const tokenSchema: Schema<Token> = object({
  token: ['token', string()],
  expires: ['expires', number()],
});
